version: "3.8"
services:
  homer:
    container_name: homer
    image: b4bz/homer:latest
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/ragnar-b/docker/homer:/www/assets/
    ports:
      - "8081:8080"
    restart: unless-stopped
