version: "3.8"
services:
  Uptime-Kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    volumes:
      - /home/ragnar-b/docker/uptime-kuma:/app/data
    ports:
      - "3001:3001"
    dns:
      - 192.168.1.15
      - 1.1.1.1
    restart: always