version: "3.8"
services:
  homer:
    image: b4bz/homer:latest
    ports:
      - "8081:8080"
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - homer:/www/assets/
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  homer:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.1.29,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nolock"
      device: ":/volume1/docker/homer"

