version: "3.8"
services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "3080:80/tcp"
    environment:
      - TZ=Europe/Amsterdam
      - WEBPASSWORD=DrukH4r1
    volumes:
      - pihole_config:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  pihole_config:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.1.29,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nolock"
      device: ":/volume1/docker/pihole/config"
  pihole_dnsmasq:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.1.29,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nolock"
      device: ":/volume1/docker/pihole/dnsmasq.d"
