version: "3.8"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - unifi:/config
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8443:8443"
      - "1900:1900/udp" #optional
      - "8843:8843" #optional
      - "8880:8880" #optional
      - "6789:6789" #optional
      - "5514:5514/udp" #optional
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  unifi:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.1.29,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nolock"
      device: ":/volume1/docker/unifi"
