version: "3.8"
services:
  watchtower:
#    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_SCHEDULE=0 0 5 * * ?
      - TZ=Europe/Amsterdam
#    restart: unless-stopped
    deploy:
      mode: global
